openapi: 3.1.0
info:
  title: Quality Gate API
  description: A microservice for managing API Quality-Gate Configurations
  version: 1.0.0
  x-api-name: quality-gate
  x-service-name: quality-gate-api
paths:
  /api/rest/v1/quality-gates:
    get:
      operationId: getAllQualityGates
      summary: Retrieve all Quality-Gate Configurations
      description: Returns a list of all available Quality-Gate Configurations
      tags:
        - quality-gate
      parameters:
        - name: page
          in: query
          description: 'Page number (0-based index)'
          required: false
          schema:
            type: integer
            minimum: 0
        - name: size
          in: query
          description: 'Number of items per page'
          required: false
          schema:
            type: integer
            minimum: 1
        - name: sort
          in: query
          description: 'Sorting criteria in the format: property,(asc|desc). Defaults to initiatedAt,desc'
          required: false
          schema:
            type: string
            example: initiatedAt,desc
      responses:
        '200':
          description: A list of Quality-Gate Configurations
          headers:
            X-Total-Count:
              description: 'Total number of Quality-Gate Configurations available'
              schema:
                type: integer
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/QualityGateConfig'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
    post:
      operationId: createQualityGate
      summary: Create a new Quality-Gate Configuration
      description: Creates a new Quality-Gate Configuration with specified criteria
      tags:
        - quality-gate
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/QualityGateConfig'
      responses:
        '201':
          description: Configuration created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/QualityGateConfig'
          headers:
            Location:
              required: true
              schema:
                type: string
                format: uri
              description: URI to the newly created Quality-Gate Configuration
        '400':
          description: Invalid request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '409':
          description: Configuration name already exists
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  /api/rest/v1/quality-gates/{name}:
    get:
      operationId: getQualityGateByName
      summary: Retrieve a specific Quality-Gate Configuration
      description: Returns a Quality-Gate Configuration by name
      tags:
        - quality-gate
      parameters:
        - name: name
          in: path
          description: Name of the Quality-Gate Configuration to retrieve
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Quality gate configuration
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/QualityGateConfig'
        '404':
          description: Configuration not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
    put:
      operationId: updateQualityGate
      summary: Update a Quality-Gate Configuration
      description: Updates an existing Quality-Gate Configuration
      tags:
        - quality-gate
      parameters:
        - name: name
          in: path
          description: Name of the Quality-Gate Configuration to update
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/QualityGateConfig'
      responses:
        '200':
          description: Configuration updated successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/QualityGateConfig'
        '400':
          description: Invalid request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '404':
          description: Configuration not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
    delete:
      operationId: deleteQualityGate
      summary: Delete a Quality-Gate Configuration
      description: Deletes a Quality-Gate Configuration by name
      tags:
        - quality-gate
      parameters:
        - name: name
          in: path
          description: Name of the Quality-Gate Configuration to delete
          required: true
          schema:
            type: string
      responses:
        '204':
          description: Configuration deleted successfully
        '404':
          description: Configuration not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  /api/rest/v1/criteria/openapi:
    get:
      operationId: listOpenApiCriteria
      summary: List OpenAPI Coverage Criteria
      description: Returns all available OpenAPI coverage criteria used for quality gate evaluation
      tags:
        - criteria
      responses:
        '200':
          description: List of OpenAPI criteria
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/OpenApiCriterion'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
components:
  schemas:
    QualityGateConfig:
      type: object
      required:
        - name
        - isPredefined
        - openApiCriteria
      properties:
        name:
          type: string
          description: Unique name for the Quality-Gate Configuration
          example: 'basic-coverage'
          minLength: 1
          maxLength: 64
        description:
          type: string
          description: Optional description of the Quality-Gate Configuration
          example: 'Basic coverage criteria for API testing'
          maxLength: 256
        isPredefined:
          type: boolean
          description: Whether the Quality-Gate Configuration is predefined or not
          default: false
        openApiCriteria:
          type: array
          description: List of OpenAPI criteria IDs used in this configuration
          items:
            type: string
            minLength: 1
            maxLength: 32
          example: ['PATH_COVERAGE']
    OpenApiCriterion:
      type: object
      required:
        - id
        - name
      properties:
        id:
          type: string
          description: Unique ID of the criterion
          example: PATH_COVERAGE
          minLength: 1
          maxLength: 32
        name:
          type: string
          description: Human-readable name
          example: Path Coverage
          minLength: 1
          maxLength: 64
        description:
          type: string
          description: Optional description of what the criterion checks
          example: Every API endpoint has at least one request
          minLength: 1
          maxLength: 256
    Error:
      type: object
      required:
        - code
        - message
      properties:
        code:
          type: string
          example: 'INVALID_REQUEST'
        message:
          type: string
          example: 'Invalid request parameters'
