version: 2
assignees:
  - bbortt
labels:
  - 'severity:medium'
  - 'status:ready-for-review '
  - 'type:deps'
updates:
  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'daily'
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'daily'
  - package-ecosystem: 'npm'
    directory: '/microservices/api-gateway/'
    schedule:
      interval: 'daily'
  - package-ecosystem: 'maven'
    directory: '/'
    schedule:
      interval: 'daily'
  - package-ecosystem: 'gitsubmodule'
    directory: '/opentelemetry-proto'
    schedule:
      interval: 'weekly'
  - package-ecosystem: 'docker-compose'
    directory: '/dev'
    schedule:
      interval: 'weekly'
