name: 'snow-white'

networks:
  default:
    name: podman
  internal:
    name: snow-white

services:
  otel-collector:
    image: otel/opentelemetry-collector-contrib:0.161.0
    volumes:
      - ./microservices/api-index-api/target/otel-collector/traces.json:/data/traces-api-index-api.json
      - ./microservices/quality-gate-api/target/otel-collector/traces.json:/data/traces-quality-gate-api.json
      - ./microservices/report-coordinator-api/target/otel-collector/traces.json:/data/traces-report-coordinator-api.json
      - ./otel-collector/config.yaml:/etc/otelcol-contrib/config.yaml
    ports:
      - '13133:13133' # health_check extension
      - '4317:4317' # OTLP gRPC receiver
      - '4318:4318' # OTLP http receiver
    deploy:
      resources:
        reservations:
          cpus: '0.1'
          memory: '128m'
        limits:
          cpus: '0.2'
          memory: '512m'
    depends_on:
      kafka:
        condition: service_healthy
    restart: on-failure
    networks:
      - default
      - internal

  grafana:
    image: grafana/otel-lgtm:0.33.0
    networks:
      - internal

  kafka:
    image: confluentinc/cp-kafka:${CP_KAFKA_VERSION:-8.3.2}
    environment:
      # Cluster / broker identity
      KAFKA_NODE_ID: 1
      KAFKA_BROKER_ID: 1
      CLUSTER_ID: 'ZTkwOTM2MzQyYWJmNDM5Ym' # run "kafka-storage random-uuid"
      KAFKA_PROCESS_ROLES: 'broker,controller'

      # Listener setup
      KAFKA_LISTENERS: 'PLAINTEXT://:9092,CONTROLLER://:9093,EXTERNAL://:9094'
      KAFKA_ADVERTISED_LISTENERS: 'PLAINTEXT://localhost:9092,EXTERNAL://kafka:9094'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: 'CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,EXTERNAL:PLAINTEXT'
      KAFKA_CONTROLLER_QUORUM_VOTERS: '1@kafka:9093'
      KAFKA_CONTROLLER_LISTENER_NAMES: 'CONTROLLER'

      # Other essential configs
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'false'
    deploy:
      resources:
        reservations:
          cpus: '0.5'
          memory: '1g'
        limits:
          cpus: '1'
          memory: '2g'
    healthcheck:
      test: kafka-topics --bootstrap-server localhost:9092 --list || exit 1
      interval: 3s
      timeout: 5s
      retries: 20
    restart: on-failure
    networks:
      - internal

  postgres:
    image: postgres:${POSTGRES_VERSION:-18-alpine}
    shm_size: 128mb
    environment:
      POSTGRES_USER: 'snow-white'
      POSTGRES_PASSWORD: 'snow-white'
    volumes:
      - ./postgres/data/:/var/lib/postgresql
      - ./dev/postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U snow-white -d postgres']
      interval: 5s
      timeout: 5s
      retries: 5
    restart: on-failure
    networks:
      - internal

  microservices.api-gateway:
    image: ${CONTAINER_REGISTRY:-ghcr.io}/bbortt/snow-white/api-gateway:${SNOW_WHITE_BUILD:-latest}
    hostname: api-gateway
    environment:
      LOGGING_PATTERN_CONSOLE: '%d{yyyy-MM-dd''T''HH:mm:ss.SSSXXX} level="%level" thread="%thread" logger="%logger{2}"%replace(%mdc{traceId}){^(.+)$, '' traceId="$1"''} msg="%msg"%n%ex'
      OTEL_EXPORTER_OTLP_PROTOCOL: 'grpc'
      OTEL_EXPORTER_OTLP_ENDPOINT: 'http://otel-collector:4317'
      SNOW_WHITE_API_GATEWAY_PUBLIC-URL: 'http://localhost'
      SNOW_WHITE_API_GATEWAY_API-INDEX-API-URL: 'http://api-index-api:8080'
      SNOW_WHITE_API_GATEWAY_QUALITY-GATE-API-URL: 'http://quality-gate-api:8080'
      SNOW_WHITE_API_GATEWAY_REPORT-COORDINATOR-API-URL: 'http://report-coordinator-api:8080'
    ports:
      - '80:8080'
    deploy:
      resources:
        reservations:
          cpus: '0.25'
          memory: '512m'
        limits:
          cpus: '0.5'
          memory: '512m'
    depends_on:
      otel-collector:
        condition: service_started
      microservices.api-index-api:
        condition: service_started
      microservices.quality-gate-api:
        condition: service_started
      microservices.report-coordinator-api:
        condition: service_started
    healthcheck:
      test: wget -O - http://localhost:8090/management/health | grep UP || exit 1
      interval: 1s
      timeout: 5s
      retries: 12
    restart: on-failure
    networks:
      - default
      - internal

  microservices.api-index-api:
    image: ${CONTAINER_REGISTRY:-ghcr.io}/bbortt/snow-white/api-index-api:${SNOW_WHITE_BUILD:-latest}
    hostname: api-index-api
    environment:
      LOGGING_PATTERN_CONSOLE: '%d{yyyy-MM-dd''T''HH:mm:ss.SSSXXX} level="%level" thread="%thread" logger="%logger{2}"%replace(%mdc{traceId}){^(.+)$, '' traceId="$1"''} msg="%msg"%n%ex'
      MANAGEMENT_TRACING_SAMPLING_PROBABILITY: 1.0
      OTEL_EXPORTER_OTLP_ENDPOINT: 'http://otel-collector:4318'
      SNOW_WHITE_API_INDEX_PUBLIC_API_GATEWAY_URL: 'http://localhost'
      SPRING_DATASOURCE_URL: 'jdbc:postgresql://postgres:5432/api-index-api'
      SPRING_DATASOURCE_USERNAME: 'api_index_app'
      SPRING_DATASOURCE_PASSWORD: 'strongpassword6'
      SPRING_FLYWAY_USER: 'api_index_flyway'
      SPRING_FLYWAY_PASSWORD: 'strongpassword5'
    deploy:
      resources:
        reservations:
          cpus: '0.1'
          memory: '128m'
        limits:
          cpus: '0.2'
          memory: '512m'
    depends_on:
      otel-collector:
        condition: service_started
      postgres:
        condition: service_healthy
    restart: on-failure
    networks:
      - internal

  microservices.openapi-coverage-stream:
    image: ${CONTAINER_REGISTRY:-ghcr.io}/bbortt/snow-white/openapi-coverage-stream:${SNOW_WHITE_BUILD:-latest}
    hostname: openapi-coverage-stream
    environment:
      TEMPO_URL: 'http://grafana:3200'
      TEMPO_USERNAME: 'snow-white'
      TEMPO_PASSWORD: 'snow-white'
      LOGGING_PATTERN_CONSOLE: '%d{yyyy-MM-dd''T''HH:mm:ss.SSSXXX} level="%level" thread="%thread" logger="%logger{2}"%replace(%mdc{traceId}){^(.+)$, '' traceId="$1"''} msg="%msg"%n%ex'
      OTEL_EXPORTER_OTLP_PROTOCOL: 'grpc'
      OTEL_EXPORTER_OTLP_ENDPOINT: 'http://otel-collector:4317'
      SNOW_WHITE_OPENAPI_COVERAGE_STREAM_API-INDEX_BASE-URL: 'http://api-index-api:8080'
      SNOW_WHITE_OPENAPI_COVERAGE_STREAM_CALCULATION-REQUEST-TOPIC: 'snow-white-calculation-request'
      SNOW_WHITE_OPENAPI_COVERAGE_STREAM_INIT-TOPICS: 'true'
      SNOW_WHITE_OPENAPI_COVERAGE_STREAM_OPENAPI-CALCULATION-RESPONSE-TOPIC: 'snow-white-openapi-calculation-response'
      SPRING_KAFKA_BOOTSTRAP_SERVERS: 'kafka:9094'
    deploy:
      resources:
        reservations:
          cpus: '0.25'
          memory: '512m'
        limits:
          cpus: '0.5'
          memory: '512m'
    depends_on:
      grafana:
        condition: service_started
      otel-collector:
        condition: service_started
    restart: on-failure
    networks:
      - internal

  microservices.quality-gate-api:
    image: ${CONTAINER_REGISTRY:-ghcr.io}/bbortt/snow-white/quality-gate-api:${SNOW_WHITE_BUILD:-latest}
    hostname: quality-gate-api
    environment:
      LOGGING_PATTERN_CONSOLE: '%d{yyyy-MM-dd''T''HH:mm:ss.SSSXXX} level="%level" thread="%thread" logger="%logger{2}"%replace(%mdc{traceId}){^(.+)$, '' traceId="$1"''} msg="%msg"%n%ex'
      MANAGEMENT_TRACING_SAMPLING_PROBABILITY: 1.0
      OTEL_EXPORTER_OTLP_ENDPOINT: 'http://otel-collector:4318'
      SNOW_WHITE_QUALITY_GATE_API_PUBLIC-API-GATEWAY-URL: 'http://localhost'
      SPRING_DATASOURCE_URL: 'jdbc:postgresql://postgres:5432/quality-gate-api'
      SPRING_DATASOURCE_USERNAME: 'quality_gate_app'
      SPRING_DATASOURCE_PASSWORD: 'strongpassword4'
      SPRING_FLYWAY_USER: 'quality_gate_flyway'
      SPRING_FLYWAY_PASSWORD: 'strongpassword3'
    deploy:
      resources:
        reservations:
          cpus: '0.1'
          memory: '128m'
        limits:
          cpus: '0.2'
          memory: '512m'
    depends_on:
      otel-collector:
        condition: service_started
      postgres:
        condition: service_healthy
    restart: on-failure
    networks:
      - internal

  microservices.report-coordinator-api:
    image: ${CONTAINER_REGISTRY:-ghcr.io}/bbortt/snow-white/report-coordinator-api:${SNOW_WHITE_BUILD:-latest}
    hostname: report-coordinator-api
    environment:
      LOGGING_PATTERN_CONSOLE: '%d{yyyy-MM-dd''T''HH:mm:ss.SSSXXX} level="%level" thread="%thread" logger="%logger{2}"%replace(%mdc{traceId}){^(.+)$, '' traceId="$1"''} msg="%msg"%n%ex'
      MANAGEMENT_TRACING_SAMPLING_PROBABILITY: 1.0
      OTEL_EXPORTER_OTLP_ENDPOINT: 'http://otel-collector:4318'
      SNOW_WHITE_REPORT_COORDINATOR_API_API-INDEX_BASE-URL: 'http://api-index-api:8080'
      SNOW_WHITE_REPORT_COORDINATOR_API_CALCULATION-REQUEST-TOPIC: 'snow-white-calculation-request'
      SNOW_WHITE_REPORT_COORDINATOR_API_INIT-TOPICS: 'true'
      SNOW_WHITE_REPORT_COORDINATOR_API_OPENAPI-CALCULATION-RESPONSE_TOPIC: 'snow-white-openapi-calculation-response'
      SNOW_WHITE_REPORT_COORDINATOR_API_PUBLIC_API_GATEWAY_URL: 'http://localhost'
      SNOW_WHITE_REPORT_COORDINATOR_API_QUALITY-GATE-API_BASE-URL: 'http://quality-gate-api:8080'
      SPRING_DATASOURCE_URL: 'jdbc:postgresql://postgres:5432/report-coordinator-api'
      SPRING_DATASOURCE_USERNAME: 'report_coord_app'
      SPRING_DATASOURCE_PASSWORD: 'strongpassword2'
      SPRING_FLYWAY_USER: 'report_coord_flyway'
      SPRING_FLYWAY_PASSWORD: 'strongpassword1'
      SPRING_KAFKA_BOOTSTRAP_SERVERS: 'kafka:9094'
    deploy:
      resources:
        reservations:
          cpus: '0.1'
          memory: '128m'
        limits:
          cpus: '0.2'
          memory: '512m'
    depends_on:
      kafka:
        condition: service_healthy
      otel-collector:
        condition: service_started
      postgres:
        condition: service_healthy
      microservices.quality-gate-api:
        condition: service_started
    restart: on-failure
    networks:
      - internal
