server:
  port: ${APPL_HTTP_SERVER_PORT:8080}
spring:
  application:
    name:
  datasource:
    url: ${appl.jdbc.url}
    username: ${appl.jdbc.username}
    password: ${appl.jdbc.password}
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
grpc:
  server:
    port: ${APPL_GRPC_SERVER_PORT:9090}
