name: 'snow-white dev'

services:
  sonarqube:
    image: sonarqube:9.9.8-community
    container_name: sonarqube
    restart: unless-stopped
    ports:
      - '9000:9000'
      - '9092:9092'
    environment:
      SONAR_JDBC_URL: jdbc:postgresql://db/sonarqube
      SONAR_JDBC_USERNAME: sonar
      SONAR_JDBC_PASSWORD: sonar
    depends_on:
      - db

  db:
    image: postgres:17.5-alpine
    container_name: sonarqube_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: sonar
      POSTGRES_PASSWORD: sonar
      POSTGRES_DB: sonarqube
    volumes:
      - sonarqube_db_data:/var/lib/postgresql/data

volumes:
  sonarqube_db_data:
