snow:
  white:
    report:
      coordinator:
        api:
          calculation-request-topic: snow-white-calculation-request
          openapi-calculation-response:
            topic: snow-white-openapi-calculation-response
          public-api-gateway-url: http://localhost:8090
          quality-gate-api-url: http://localhost:8081
server:
  port: 8084
spring:
  devtools:
    livereload:
      enabled: true
  datasource:
    jdbc-url: jdbc:h2:mem:report-coordinator-api;MODE=PostgreSQL
    username: sa
    password: password
  flyway:
    enabled: false
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: create-drop
