quarkus:
  datasource:
    username: ${APPL_JDBC_USERNAME}
    password: ${APPL_JDBC_PASSWORD}
    reactive:
      max-size: 20
      url: ${APPL_DATASOURCE_REACTIVE_URL}
  hibernate-orm:
    database:
      generation: create-drop
  http:
    port: 8080
'%dev':
  quarkus:
    datasource:
      username: snow_white
      password: snow_white_password
      reactive:
        max-size: 10
        url: postgresql://localhost:5432/snow_white
  hibernate-orm:
    database:
      generation: create-drop
