quarkus:
  datasource:
    username: ${APPL_JDBC_USERNAME}
    password: ${APPL_JDBC_PASSWORD}
    jdbc:
      url: ${APPL_JDBC_URL}
  hibernate-orm:
    database:
      generation: validate
  http:
    port: 8080
'%dev':
  quarkus:
    datasource:
      username: snow_white
      password: snow_white_password
      jdbc:
        url: jdbc:postgresql://localhost:5432/snow_white
'%h2':
  quarkus:
    datasource:
      db-kind: h2
      username: sa
      password: password
      jdbc:
        url: jdbc:h2:mem:snow_white;MODE=PostgreSQL
    hibernate-orm:
      database:
        generation: drop-and-create
