/*
 * THIS FILE IS GENERATED BY CLEW - DO NOT EDIT MANUALLY
 *
 * Run `clew spec` to regenerate.
 *
 * @clew homepage: https://ariadne-thread.io
 * @clew connector-type: req-as-code
 * @clew generator-type: java
 * @clew spec-set: ARCH
 */

package clew.traceables.clew;

public enum ArchTraceables {
  ARCH_001_PLUGGABLE_INFLUXDB_OR_TEMPO_TELEMETRY_BACKEND("ARCH-001");

  private final String id;

  ArchTraceables(String id) {
    this.id = id;
  }

  public String id() {
    return this.id;
  }
}
