/*
 * THIS FILE IS GENERATED BY CLEW - DO NOT EDIT MANUALLY
 *
 * Run `clew spec` to regenerate.
 *
 * @clew homepage: https://ariadne-thread.io
 * @clew connector-type: req-as-code
 * @clew generator-type: java
 * @clew spec-set: ARCH
 */

package clew.traceables.clew;

public enum ArchTraceables {
  ARCH_001_PLUGGABLE_INFLUXDB_OR_TEMPO_TELEMETRY_BACKEND("ARCH-001"),
  ARCH_002_CRITERIA_METADATA_OWNED_BY_ENUM("ARCH-002"),
  ARCH_003_IDEMPOTENT_ORDERED_STARTUP_SEEDING("ARCH-003"),
  ARCH_004_PER_API_TEST_FAN_OUT_KEYED_BY_CALCULATION_ID("ARCH-004"),
  ARCH_005_DISPATCH_AFTER_TRANSACTION_COMMIT("ARCH-005"),
  ARCH_006_REPORT_STATUS_PERSISTED_AS_STABLE_CODE("ARCH-006"),
  ARCH_007_REQUIRED_ATTRIBUTE_KEYS_COMPUTED_ONCE_BY_CALLER("ARCH-007"),
  ARCH_008_BACKEND_SERVICES_ADDRESSED_BY_PATH_PREFIX_WITH_AGGREGATED_OPENAPI_DOCS(
    "ARCH-008"
  ),
  ARCH_009_STATIC_ASSETS_BYPASS_THE_SECURITY_FILTER_CHAIN("ARCH-009");

  private final String id;

  ArchTraceables(String id) {
    this.id = id;
  }

  public String id() {
    return this.id;
  }
}
