/*
 * THIS FILE IS GENERATED BY CLEW - DO NOT EDIT MANUALLY
 *
 * Run `clew spec` to regenerate.
 *
 * @clew homepage: https://ariadne-thread.io
 * @clew connector-type: req-as-code
 * @clew generator-type: java
 * @clew spec-set: CON
 */

package clew.traceables.clew;

public enum ConTraceables {
  CON_001_DETERMINISTIC_ANALYSIS_RESULTS("CON-001"),
  CON_002_TOLERATE_DEPENDENCY_OUTAGES("CON-002"),
  CON_003_PREDEFINED_QUALITY_GATES_ARE_IMMUTABLE("CON-003"),
  CON_004_COVERAGE_RATIO_IS_ALWAYS_BOUNDED_AND_WELL_DEFINED("CON-004"),
  CON_005_API_CREATED_GATES_ARE_NEVER_PREDEFINED("CON-005");

  private final String id;

  ConTraceables(String id) {
    this.id = id;
  }

  public String id() {
    return this.id;
  }
}
