/*
 * THIS FILE IS GENERATED BY CLEW - DO NOT EDIT MANUALLY
 *
 * Run `clew spec` to regenerate.
 *
 * @clew homepage: https://ariadne-thread.io
 * @clew connector-type: req-as-code
 * @clew generator-type: java
 * @clew spec-set: NF
 */

package clew.traceables.clew;

public enum NfTraceables {
  NF_001_OPERATIONAL_OBSERVABILITY("NF-001"),
  NF_002_UNATTENDED_OPERATION("NF-002"),
  NF_003_SCALABILITY_WITHOUT_REDESIGN("NF-003"),
  NF_004_CICD_SUITABLE_PERFORMANCE("NF-004"),
  NF_005_CLEAR_FAILURE_FEEDBACK("NF-005"),
  NF_006_BOUNDED_TELEMETRY_FETCH_FOOTPRINT("NF-006"),
  NF_007_TEMPO_SEARCH_LIMIT_IS_OPERATOR_CONFIGURABLE("NF-007"),
  NF_008_TEMPO_SEARCH_RETURNS_EVERY_MATCHED_SPAN_PER_TRACE("NF-008");

  private final String id;

  NfTraceables(String id) {
    this.id = id;
  }

  public String id() {
    return this.id;
  }
}
