/*
 * THIS FILE IS GENERATED BY CLEW - DO NOT EDIT MANUALLY
 *
 * Run `clew spec` to regenerate.
 *
 * @clew homepage: https://ariadne-thread.io
 * @clew connector-type: req-as-code
 * @clew generator-type: java
 * @clew spec-set: STK
 */

package clew.traceables.clew;

public enum StkTraceables {
  STK_001_CORRELATE_SPECS_WITH_TELEMETRY("STK-001"),
  STK_002_BLACK_BOX_TESTS_AS_TELEMETRY_SOURCE("STK-002"),
  STK_003_NO_APP_CODE_CHANGES_BEYOND_OTEL("STK-003");

  private final String id;

  StkTraceables(String id) {
    this.id = id;
  }

  public String id() {
    return this.id;
  }
}
