/*
 * THIS FILE IS GENERATED BY CLEW - DO NOT EDIT MANUALLY
 *
 * Run `clew spec` to regenerate.
 *
 * @clew homepage: https://ariadne-thread.io
 * @clew connector-type: req-as-code
 * @clew generator-type: java
 * @clew spec-set: SW
 */

package clew.traceables.clew;

public enum SwTraceables {
  SW_001_STRUCTURAL_CALL_COVERAGE("SW-001"),
  SW_002_RESPONSE_CODE_COVERAGE_TREATS_DEFAULT_AS_WILDCARD("SW-002"),
  SW_003_UNDOCUMENTED_RESPONSE_CODE_DETECTION("SW-003"),
  SW_004_PARAMETER_COVERAGE_MATCHES_BY_TOKEN_NOT_SUBSTRING("SW-004"),
  SW_005_CONTENT_TYPE_COVERAGE("SW-005"),
  SW_006_REQUIRED_ERROR_FIELDS_COVERAGE("SW-006"),
  SW_007_DEFAULT_RESPONSE_KEY_IS_THE_ERROR_FALLBACK_CASE("SW-007"),
  SW_008_KAFKA_AS_ASYNC_CALCULATION_DRIVER("SW-008");

  private final String id;

  SwTraceables(String id) {
    this.id = id;
  }

  public String id() {
    return this.id;
  }
}
