/*
 * THIS FILE IS GENERATED BY CLEW - DO NOT EDIT MANUALLY
 *
 * Run `clew spec` to regenerate.
 *
 * @clew homepage: https://ariadne-thread.io
 * @clew connector-type: req-as-code
 * @clew generator-type: java
 * @clew spec-set: SYS
 */

package clew.traceables.clew;

public enum SysTraceables {
  SYS_001_PERIODIC_SPEC_SYNC("SYS-001"),
  SYS_002_INDEXED_SPEC_LOOKUP("SYS-002"),
  SYS_003_OPENAPI_AS_INDEXED_FORMAT("SYS-003"),
  SYS_004_TELEMETRY_INGESTION_AND_CORRELATION("SYS-004"),
  SYS_005_SCOPED_TELEMETRY_INGESTION("SYS-005"),
  SYS_006_CRITERIA_BASED_EVALUATION("SYS-006"),
  SYS_007_ON_DEMAND_RECOMPUTATION("SYS-007"),
  SYS_008_QUALITY_GATE_DEFINITIONS("SYS-008"),
  SYS_009_MACHINE_CONSUMABLE_GATE_RESULT("SYS-009"),
  SYS_010_ANALYSIS_TRIGGERING("SYS-010"),
  SYS_011_BOUNDED_TIME_RESOLUTION("SYS-011"),
  SYS_012_RESULT_CONSUMPTION("SYS-012"),
  SYS_013_PRERELEASE_SPECIFICATION_INGESTION("SYS-013");

  private final String id;

  SysTraceables(String id) {
    this.id = id;
  }

  public String id() {
    return this.id;
  }
}
