#
# Copyright (c) 2026 Timon Borter <timon.borter@gmx.ch>
# Licensed under the Polyform Small Business License 1.0.0
# See LICENSE file for full details.
#

spring.application.name=application

logging.pattern.console=%d{yyyy-MM-dd'T'HH:mm:ss.SSSXXX} logLevel=%level threadName="%thread" logger=%logger{1}%replace( traceId=%X{traceId}){' traceId=$', ''}%replace( spanId=%X{spanId}){' spanId=$', ''} : %msg%n
server.tomcat.accesslog.enabled=true
server.tomcat.accesslog.pattern=%{yyyy-MM-dd'T'HH:mm:ss.SSSXXX}t logLevel=ACCESS %{org.apache.catalina.AccessLog.RemoteAddr}r method=%m uri=%U traceparent="%{traceparent}i" status=%s
