io:
  github:
    bbortt:
      snow:
        white:
          microservices:
            report:
              coordination:
                service:
                  quality-gate-api-url: http://localhost:8082
server:
  port: 8084
spring:
  datasource:
    jdbc-url: jdbc:h2:mem:report-coordination;MODE=PostgreSQL
    username: sa
    password: password
  h2:
    console:
      enabled: true
