import { precacheAndRoute } from 'workbox-precaching';
import { registerRoute, NavigationRoute } from 'workbox-routing';
import { NetworkFirst, StaleWhileRevalidate } from 'workbox-strategies';
import { warmStrategyCache } from 'workbox-recipes';

// Precache all the assets generated by webpack
precacheAndRoute(self.__WB_MANIFEST);

const OFFLINE_URL = '/offline.html';
const offlineStrategy = new NetworkFirst({
  cacheName: 'offline-cache',
});

warmStrategyCache({
  urls: [OFFLINE_URL],
  strategy: offlineStrategy,
});

// Handle navigation requests
const navigationRoute = new NavigationRoute(
  new NetworkFirst({
    cacheName: 'navigations',
    plugins: [
      {
        // Fallback to the offline page if the network is not available
        handlerDidError: async () => {
          return await caches.match(OFFLINE_URL);
        },
      },
    ],
  }),
);
registerRoute(navigationRoute);

// Handle API requests
registerRoute(
  /^https:\/\/snow-white\.execute-api\.eu-central-1\.amazonaws\.com\/api\/.*/,
  new StaleWhileRevalidate({
    cacheName: 'api',
    plugins: [
      {
        // Ensure that only successful responses are cached
        fetchDidSucceed: async ({ response }) => {
          if (response.status >= 400) {
            return null;
          }
          return response;
        },
      },
    ],
  }),
);

self.addEventListener('online', () => {
  // Perform actions when the app comes online
  console.log('You are online!');
  // You can also send a message to the client to update the UI
  self.clients.matchAll().then(clients => {
    clients.forEach(client => {
      client.postMessage({ type: 'online' });
    });
  });
});

self.addEventListener('offline', () => {
  // Perform actions when the app goes offline
  console.log('You are offline!');
  // You can also send a message to the client to update the UI
  self.clients.matchAll().then(clients => {
    clients.forEach(client => {
      client.postMessage({ type: 'offline' });
    });
  });
});
