openapi: 3.0.3
info:
  title: Report Coordination Service
  description: A gateway service dispatching jobs for all microservice. A single entrypoint into the system for all user interfaces.
  version: 1.0.0
  x-api-name: quality-gate
  x-service-name: report-coordination-service
paths:
  /api/rest/v1/quality-gates/{qualityGateConfigName}/calculate:
    post:
      operationId: calculateQualityGate
      summary: 'Initiate asynchronous quality gate calculation for a specific service and API'
      description: >
        Starts an asynchronous calculation of a previously configured quality gate for a specified service.
        Returns a UUID that can be used to query the status and results of the calculation.
      tags:
        - quality-gate
      parameters:
        - name: qualityGateConfigName
          in: path
          description: 'The name of the quality gate that must be previously configured'
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: './components/QualityGateCalculationRequest.yml'
      responses:
        '202':
          description: 'Quality gate calculation initiated successfully'
          content:
            application/json:
              schema:
                $ref: './components/QualityGateReport.yml'
        '400':
          description: 'Bad request, such as missing required parameters or invalid format'
          content:
            application/json:
              schema:
                $ref: './components/Error.yml'
        '404':
          description: 'Quality gate name not found'
          content:
            application/json:
              schema:
                $ref: './components/Error.yml'
        '500':
          description: 'Internal server error'
          content:
            application/json:
              schema:
                $ref: './components/Error.yml'
