openapi: 3.1.0
info:
  title: Report Coordination Service
  description: A gateway service dispatching jobs for all microservice. A single entrypoint into the system for all user interfaces.
  version: 1.0.0
  x-api-name: report
  x-service-name: report-coordination-service
paths:
  /api/rest/v1/reports:
    get:
      operationId: listQualityGateReports
      summary: 'List all Quality-Gate Reports'
      description: 'Returns a paginated list of all Quality-Gate Reports'
      tags:
        - report
      parameters:
        - name: page
          in: query
          description: 'Page number (0-based index)'
          required: false
          schema:
            type: integer
            minimum: 0
        - name: size
          in: query
          description: 'Number of items per page'
          required: false
          schema:
            type: integer
            minimum: 1
        - name: sort
          in: query
          description: 'Sorting criteria in the format: property,(asc|desc). Defaults to initiatedAt,desc'
          required: false
          schema:
            type: string
            example: initiatedAt,desc
      responses:
        '200':
          description: 'Paginated list of Quality-Gate Reports'
          headers:
            X-Total-Count:
              description: 'Total number of Quality-Gate Reports available'
              schema:
                type: integer
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: './components/QualityGateReport.yml'
        '500':
          description: 'Internal server error'
          content:
            application/json:
              schema:
                $ref: './components/Error.yml'

  /api/rest/v1/reports/{calculationId}:
    get:
      operationId: getReportByCalculationId
      summary: 'Get Quality-Gate calculation reports'
      description: 'Retrieves the status and reports of an asynchronous Quality-Gate calculation'
      tags:
        - report
      parameters:
        - name: calculationId
          in: path
          description: 'The UUID of the calculation job returned from the POST request'
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: 'Quality-Gate calculation completed successfully'
          content:
            application/json:
              schema:
                $ref: './components/QualityGateReport.yml'
        '202':
          description: 'Calculation is still in progress'
          content:
            application/json:
              schema:
                $ref: './components/QualityGateReport.yml'
        '404':
          description: 'Calculation ID not found'
          content:
            application/json:
              schema:
                $ref: './components/Error.yml'
        '500':
          description: 'Internal server error'
          content:
            application/json:
              schema:
                $ref: './components/Error.yml'
  /api/rest/v1/reports/{calculationId}/junit:
    get:
      operationId: getReportByCalculationIdAsJUnit
      summary: 'Get Quality-Gate report in JUnit XML format'
      description: 'Retrieves the status and results of an asynchronous Quality-Gate calculation formatted as JUnit XML'
      tags:
        - report
      parameters:
        - name: calculationId
          in: path
          description: 'The UUID of the calculation job returned from the POST request'
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: 'Quality-Gate calculation completed successfully'
          content:
            application/xml:
              schema:
                type: string
                format: binary
        '202':
          description: 'Calculation is still in progress'
          content:
            application/json:
              schema:
                $ref: './components/QualityGateReport.yml'
        '404':
          description: 'Calculation ID not found'
          content:
            application/json:
              schema:
                $ref: './components/Error.yml'
        '500':
          description: 'Internal server error'
          content:
            application/json:
              schema:
                $ref: './components/Error.yml'
