name: 'api-gateway: apptest'

networks:
  default:
    name: github_actions
    external: true
    driver: bridge

services:
  wiremock:
    image: wiremock/wiremock:3.1.0-alpine
    ports:
      - '9000:8080'
    restart: on-failure
    networks:
      - default
