/*
 * THIS FILE IS GENERATED BY CLEW - DO NOT EDIT MANUALLY
 *
 * Run `clew spec` to regenerate.
 *
 * @clew homepage: https://ariadne-thread.io
 * @clew connector-type: req-as-code
 * @clew generator-type: java
 * @clew spec-set: SW
 */

package clew.traceables.clew.annotation;

import static java.lang.annotation.ElementType.FIELD;
import static java.lang.annotation.ElementType.METHOD;
import static java.lang.annotation.ElementType.PACKAGE;
import static java.lang.annotation.ElementType.TYPE;
import static java.lang.annotation.RetentionPolicy.SOURCE;

import clew.traceables.clew.SwTraceables;
import java.lang.annotation.Repeatable;
import java.lang.annotation.Retention;
import java.lang.annotation.Target;

@Repeatable(ConcernsSw.Container.class)
@Target({ PACKAGE, TYPE, METHOD, FIELD })
@Retention(SOURCE)
public @interface ConcernsSw {
  SwTraceables[] value();

  @Target({ PACKAGE, TYPE, METHOD, FIELD })
  @Retention(SOURCE)
  @interface Container {
    ConcernsSw[] value();
  }
}
