io:
  github:
    bbortt:
      snow:
        white:
          kafka:
            event:
              filter:
                inbound-topic-name: snow-white_inbound
                init-topics: true
                outbound-topic-name: snow-white_outbound
