io:
  github:
    bbortt:
      snow:
        white:
          kafka:
            event:
              filter:
                consumer-mode: json
spring:
  kafka:
    consumer:
      enable-auto-commit: false
    listener:
      ack-mode: manual
    streams:
      application-id: kafka-event-filter
