version: '3.9'
services:
  # Collector
  otel-collector:
    image: otel/opentelemetry-collector:0.66.0
    command: ['--config=/etc/otel-collector-config.yaml']
    volumes:
      - ./otel-collector-config.yaml:/etc/otel-collector-config.yaml
    depends_on:
      - jaeger
      - snow-white
  # Snow-White
  snow-white:
    build: ..
    environment:
      SPRING_PROFILES_ACTIVE: dev,h2
    ports:
      - 8080:8080
  # Jaeger
  jaeger:
    image: jaegertracing/all-in-one:1.22
    environment:
      COLLECTOR_ZIPKIN_HOST_PORT: :9411
