receivers:
  otlp:
    protocols:
      grpc:
      http:
processors:
  batch:
  memory_limiter:
    # 80% of maximum memory up to 2G
    limit_mib: 820
    # 25% of limit up to 2G
    spike_limit_mib: 256
    check_interval: 5s
extensions:
  health_check: {}
  memory_ballast:
    # Memory Ballast size should be max 1/3 to 1/2 of memory.
    size_mib: 350
  zpages: {}
exporters:
  logging:
  otlp:
    endpoint: 'http://snow-white:9090'
    tls:
      insecure: true
service:
  extensions: [health_check, memory_ballast, zpages]
  pipelines:
    traces/1:
      receivers: [otlp]
      processors: [memory_limiter, batch]
      exporters: [logging, otlp]
