name: 'quality-gate-api: apptest'

networks:
  default:
    name: ${COMPOSE_NETWORK_NAME:-github_actions}
    external: true
    driver: bridge

services:
  postgres:
    image: postgres:18.6-alpine
    shm_size: 128mb
    environment:
      POSTGRES_USER: 'snow-white'
      POSTGRES_PASSWORD: 'snow-white'
    volumes:
      - ../../../../../dev/postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - '5432:5432'
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U snow-white -d postgres']
      interval: 2s
      timeout: 5s
      retries: 12
    restart: on-failure
    networks:
      - default

  otel-collector:
    image: otel/opentelemetry-collector-contrib:0.162.0
    user: '0:0'
    volumes:
      - ./otel-collector/config.yaml:/etc/otelcol-contrib/config.yaml
      - ../../../target/otel-collector:/data
    ports:
      - '4318:4318' # OTLP http receiver
    restart: on-failure
    networks:
      - default
