{{- if (index .Values "kafka-ui").enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: kafbat-ui-configmap
data:
  config.yml: |-
    kafka:
      clusters:
        - name: Snow-White
          bootstrapServers: {{ default (printf "%s.%s.svc.cluster.local.:9092" (include "snow-white.name" (dict "name" "kafka-connect" "context" .)) (include "common.names.namespace" .)) .Values.snowWhite.kafka.brokers }}
    auth:
      type: disabled
    management:
      health:
        ldap:
          enabled: false
{{- end }}
