@startuml

' Stylin'

!theme vibrant
left to right direction

package "Snow-White" {

  ' Snow-White components first

  component "API Gateway" as gate #Darkorange {
  component "Webapplication (UI)" as ui #Orange
}

component "API Index API" as index #Teal
component "API Sync Job" as sync #Darkorange
component "OTEL Event Filter Stream" as filter #Darkorange
component "OpenAPI Coverage Stream" as coverage #Darkorange
component "Quality-Gate API" as qgate #Darkorange
component "Report Coordinator API" as coordinator #Darkorange

' Third-party components next

database "InfluxDB" as influx #Teal

component "Kafka" #Teal {
queue "Inbound Topic" as inbound
queue "Outbound Topic" as outbound
queue "Request Topic" as request
queue "Response Topic" as response
}

component "Otel Collector" as otel #Teal
}

component "Backstage" as backstage #Teal
component "Service Interface Repository" as sir #Teal

' User connections (aka UI)

actor User as user
component CLI as cli #Darkorange

user <--> ui: HTTP/S

user ..> cli: uses
cli --> gate: HTTP/S

gate <--> qgate
gate <--> coordinator

' API Sync Job

sync ---> backstage : Fetch API Index
sync ---> sir : Fetch API Index
sync --> index : Store API Meta Information

' OTEL Event Filter

component "Example-Application" as app

app --> otel: gRPC or Protobuf

otel ..> inbound
inbound .down.> filter
filter <--> index: Query API Meta Information
filter .up.> outbound
outbound ..> otel
otel --> influx: Persist Telemetry Data

' Report Coordinator API

coordinator .down.> request
response .up.> coordinator

' OpenAPI Coverage Stream

request .down.> coverage
coverage <--> index: Query API Meta Information
coverage <-up-> influx: Query Telemetry Data
coverage .up.> response

legend right
<back:Darkorange>+</back> Snow-White
<back:Teal>+</back> Third Party
end legend

@enduml