snow:
  white:
    api:
      gateway:
        quality-gate-api-url: http://localhost:8081
        report-coordination-service-url: http://localhost:8084
server:
  port: 9080
springdoc:
  swagger-ui:
    urls:
      - name: quality-gate-api
        display-name: Quality-Gate API
        url: 'http://localhost:${server.port}/v3/api-docs/quality-gate-api'
      - name: report-coordination-service
        display-name: Report Coordination Service
        url: 'http://localhost:${server.port}/v3/api-docs/report-coordination-service'
