snow:
  white:
    api:
      gateway:
        quality-gate-api-url: http://localhost:8081
        report-coordinator-api-url: http://localhost:8084
server:
  port: 9080
spring:
  devtools:
    livereload:
      enabled: true
springdoc:
  swagger-ui:
    urls:
      - name: quality-gate-api
        display-name: Quality-Gate API
        url: 'http://localhost:${server.port}/v3/api-docs/quality-gate-api'
      - name: report-coordinator-api
        display-name: Report Coordinator API
        url: 'http://localhost:${server.port}/v3/api-docs/report-coordinator-api'
