io:
  github:
    bbortt:
      snow:
        white:
          microservices:
            quality:
              gate:
                api:
                  config:
                    public-api-gateway-url: http://localhost:8090
spring:
  datasource:
    jdbc-url: jdbc:h2:mem:quality-gate;MODE=PostgreSQL
    username: sa
    password: password
  h2:
    console:
      enabled: true
server:
  port: 8081
