name: build
on:
  push:
    branches-ignore:
      - release
    tags-ignore:
      - '*'
jobs:
  native-test:
    runs-on: ubuntu-20.04
    services:
      postgres:
        image: postgres:14.6-alpine
        env:
          POSTGRES_DB: snow_white_test
          POSTGRES_USER: snow_white
          POSTGRES_PASSWORD: snow_white_password
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17
      - run: ./gradlew flywayMigrateTest --no-daemon --scan
      - run: ./gradlew nativeTest --no-daemon --scan
      - uses: actions/cache@v4.1.2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
            ./node_modules
          key: ${{ runner.os }}-gradle-${{ hashFiles('build.gradle', 'package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-
