name: OpenAPI Checks

on:
  pull_request:
    branches:
      - main
    paths:
      - '.github/workflows/oasdiff.yml'
      - 'microservices/**/src/main/resources/openapi/**/*.yml'

concurrency:
  group: oasdiff-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  api:
    name: Validation
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    strategy:
      matrix:
        spec:
          [
            microservices/api-index-api/src/main/resources/openapi/v1-api-index-api.yml,
            microservices/quality-gate-api/src/main/resources/openapi/v1-criteria-api.yml,
            microservices/quality-gate-api/src/main/resources/openapi/v1-quality-gate-api.yml,
            microservices/report-coordinator-api/src/main/resources/openapi/v1-housekeeping-api.yml,
            microservices/report-coordinator-api/src/main/resources/openapi/v1-quality-gate-api.yml,
            microservices/report-coordinator-api/src/main/resources/openapi/v1-report-api.yml,
          ]
      fail-fast: false
    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1
        with:
          persist-credentials: false
      - name: Fetch References
        env:
          BASE_HREF: ${{ github.base_ref }}
        run: git fetch --depth=1 origin "$BASE_HREF"
      - name: oasdiff
        uses: oasdiff/oasdiff-action/changelog@5e81b5c380accc6b523f9d32a637ca630e33620b
        with:
          base: 'origin/${{ github.base_ref }}:${{ matrix.spec }}'
          revision: 'HEAD:${{ matrix.spec }}'
          github-token: '${{ github.token }}'
