name: Release Pipeline

on:
  push:
    branches:
      - main

jobs:
  release-please:
    name: 'Release Please'
    runs-on: ubuntu-latest
    environment: release
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: googleapis/release-please-action@v4
        with:
          release-type: maven
          token: ${{ secrets.RELEASE_PLEASE_TOKEN }}
  base-branch-analysis:
    name: 'Base Branch Analysis'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          cache: maven
          distribution: 'temurin'
          java-version: 21
      - name: Version Report
        run: ./mvnw --version
      - name: Build with Maven
        run: ./mvnw -Pprod verify
