name: Publish Artefacts

on:
  push:
    tags:
      - 'v*'

jobs:
  deploy:
    name: 'Deploy Microservices'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          cache: maven
          distribution: 'temurin'
          java-version: 21
      - name: Build with Maven
        run: ./mvnw -DskipTests -Pprod package
      - name: Build native Images
        run: ./mvnw -DskipTests -Pnative,prod -pl :kafka-event-filter,:report-coordination-service,:quality-gate-api spring-boot:build-image
