name: Release Pipeline

on:
  push:
    branches:
      - main

concurrency:
  group: mr-${{ github.ref }}
  cancel-in-progress: true

jobs:
  base-branch-analysis:
    name: 'Base Branch Analysis'
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: true
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          cache: maven
          distribution: 'temurin'
          java-version: 21
      - name: Cache SonarQube Packages
        uses: actions/cache@v4
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar
      - name: Version Report
        run: ./mvnw --version
      - name: Build with Maven
        run: ./mvnw -B -Pprod -Dfailsafe.rerunFailingTestsCount=2 verify
      - name: Sonar Analysis
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          ./mvnw -B sonar:sonar \
            -Dsonar.host.url=https://sonarcloud.io \
            -Dsonar.organization=bbortt-github \
            -Dsonar.projectKey=bbortt_snow-white
  release-please:
    name: 'Release Please'
    runs-on: ubuntu-latest
    environment: release
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: googleapis/release-please-action@v4
        with:
          release-type: maven
          token: ${{ secrets.RELEASE_PLEASE_TOKEN }}
